### PR TITLE
Move CE changes to patches

### PR DESCRIPTION
**Pull request by masakitenchi**
Not covering HSK removed Defs atm
Generated with workshop CE

### CODE REVIEW

**Comment by masakitenchi** [comment]
Current version confirmed no errors without any addons, (i.e. Parabellum, HSK more content & vile's series)

**Comment by masakitenchi** [comment]
- ./Ammo/Advanced/9x44mmCharged.xml
- ./Ammo/Advanced/BlasterBolt.xml
- ./Ammo/Advanced/BlasterPelletBolt.xml
- ./Ammo/Advanced/Laserbeam.xml
- ./Ammo/Advanced/PlasmaBolt.xml
- ./Ammo/Advanced/PlasmaPelletBolt.xml
- ./Ammo/Advanced/RailRay.xml
- ./Ammo/AmmoCategoryDefs/AmmoCategories_SK.xml
- ./Ammo/HighCaliber/20x120mm.xml
- ./Ammo/HighCaliber/30x173mm.xml
- ./Ammo/Neolithic/Ballista.xml
- ./Ammo/Neolithic/Bolts.xml
- ./Ammo/Neolithic/CatapultaBalls.xml
- ./Ammo/Neolithic/Darts.xml
- ./Ammo/Neolithic/Pillum.xml
- ./Ammo/Projectiles.xml
- ./Ammo/Rocket/130mm.xml

These are files that are not in workshop CE folder, left untouched in HSK folder currently

**Comment by masakitenchi** [comment]
Could not resolve cross-reference to Verse.ThingDef named Pa_M320K (wanter=thingDefs) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not resolve cross-reference to Verse.ThingDef named Pa_M320K (wanter=thingDefs) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not resolve cross-reference: No CombatExtended.AmmoDef named Ammo_556x45mmNATO_HE found to give to CombatExtended.AmmoLink (null -> null) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not resolve cross-reference: No Verse.ThingDef named Bullet_556x45mmNATO_HE found to give to CombatExtended.AmmoLink (null -> null) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not resolve cross-reference: No CombatExtended.AmmoDef named Ammo_556x45mmNATO_HE found to give to CombatExtended.AmmoLink (null -> null) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not resolve cross-reference: No CombatExtended.AmmoDef named Ammo_556x45mmNATO_HE found to give to CombatExtended.AmmoLink (null -> null) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not resolve cross-reference to Verse.ThingDef named Pa_M320K (wanter=thingDefs) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not resolve cross-reference to Verse.ThingDef named Pa_M320K (wanter=thingDefs) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not resolve cross-reference: No Verse.ThingDef named Bullet_556x45mmNATO_HE found to give to CombatExtended.AmmoLink (null -> null) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not resolve cross-reference: No Verse.ThingDef named Bullet_556x45mmNATO_HE found to give to CombatExtended.AmmoLink (null -> null) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

with Parabellum, HSK more content & vile's series

**Comment by masakitenchi** [comment]
Ready for review

**Comment by TheLoneTec** [comment]
ive not had a chance to try this yet, need to download and try and test it in game before i commit it. Been busy lately.

**Comment by masakitenchi** [comment]
It's fine. Also happy new year from GMT+9 🌚

**Comment by masakitenchi** [comment]
Any Progress? I've updated to latest development HEAD and hadn't had any conflict

**Pull request merged**
