### PR TITLE
Mod updates

### PR DESCRIPTION
**Pull request by ProTriforcer**
Updated some mods to 1.5. Some of them were replaced with an updated fork or a similar mod.

### CODE REVIEW

**Comment by pacas** [comment]
If you used any workshop mod not from the original author (continuation at least), you must provide license to the license thread (correct me if I am wrong)

**Comment by ProTriforcer** [comment]
Well, i found one for Cleaning Priority. The two forks have no license info whatsoever. I guess i can remove those, they're temporary anyway. The rest are just updates.

**Comment by AndreiAvinov** [comment]
@pacas I'd say we take this easy on mods that are already in HSK even if they are updates from other authors. Otherwise it will get very long (never will get done), let's be realistic.

**Comment by zakhad** [comment]
@AndreiAvinov @TheLoneTec @masakitenchi @pacas @ProTriforcer everytime we acquire/update a mod, even if it exists in hsk, the licence might have changed, in the ideal world we would see if it has or not by looking at the type of license is it MIT LGPL, etc It doesn't have to be super indepth just a match will suffice, if we don't have a entered licence into our tracker, then we must enter one. Doing this each and every time would slow down and put people off doing updates as it's busy work i agree. 

So to streamline and make mod updates as palatable as possible without killing enthusiasm, just see if we already entered in a licence for existing mods. If the mod we've acquired is a branch/fork or if author has changed, check the licence, and make a comment in the channel that it's changed, either the mod branch/fork or author.

We ideally would only ever need to do this with only new mods once we're up to date, but we've had to start tracking it ourselves from Skyarkhangle was doing. But since he's basically never around anymore these days that responsibility is passed onto the hsk successors or caretakers until his returns or should he.

**Review by AndreiAvinov — APPROVED** [review]

**Pull request merged**
