### PR TITLE
standalone collection of patches

### PR DESCRIPTION
**Pull request by ZB333ZB**
- Replace ApplyToAllDoorsPatch.dll with optimized version
- Add Water (Dubs Bad Hygiene) and Oil (Rimefeller) grid icons
- Implement float menu with tech-locked grid display options
---
See no conflicts with v1.5

### CODE REVIEW

**Comment by ZB333ZB** [comment]
[Source.zip](https://github.com/user-attachments/files/17449447/Source.zip)

**Comment by TheLoneTec** [comment]
I recommend just assigning existing research, right now your patches either add research or overwrite them which can cause issues.

**Comment by ZB333ZB** [comment]
- Removed XML patches
- added Defs settings
- updated DLLs for ToggleDBHGridsPatch and ToggleRimefellerGridsPatch
---
[Source.zip](https://github.com/user-attachments/files/17451882/Source.zip)

**Comment by TheLonerD** [comment]
@ZB333ZB в исходниках (в двух приложенных архивах сверху source.zip) потерялся файл `ApplyToAllDoorsPatch`

**Comment by TheLoneTec** [comment]
Thanks, I have noticed this by the way, I just have a set tike u set aside for reviewing and meeting pull requests 👍

**Comment by ZB333ZB** [comment]
The ApplyToAllDoorsPatch source code is the same. I just noticed that I had uploaded a draft version in the previous PR.
[ApplyToAllDoorsPatch.zip](https://github.com/user-attachments/files/17463364/ApplyToAllDoorsPatch.zip)

**Comment by TheLonerD** [comment]
Lgtm

**Comment by ZB333ZB** [comment]
[ApplyTo~+AutoRebuild~Sources.zip](https://github.com/user-attachments/files/17532316/ApplyTo.%2BAutoRebuild.Sources.zip)

**Comment by ZB333ZB** [comment]
Replaced laggy floatmenu with EnhancedDefSelector in scenario editor for large lists. Features fixed popup with virtual scrolling and built-in search

**Pull request merged**
