### PR TITLE
recipe moving

### PR DESCRIPTION
**Pull request by sidfu**
added a cloned butcher table to spread bills out
removed sand and gravel from specific stone recipes again(this is so people can manage their stone easier)
ce patched jt field surgery liquor

### CODE REVIEW

**Comment by Rhyssia** [comment]
Why remove Sand+Rubble byproducts from Block Recipe? [7be125a]

**Comment by zakhad** [comment]
I also prefer having the by products, since they stack into huge stacks, only real problem with it is moving it to another location when you have like 5000 units or so lol

**Comment by Rhyssia** [comment]
@zakhad The by products are still there on a few recipes. Was removed to make a work around for "Do until X"

**Comment by zakhad** [comment]
Well as long as it's clearly stated otherwise someone will report it as a bug or some such.

**Comment by sidfu** [comment]
its onbly for the 4 secific stone recpie bills on the hand machine tabble. the generic make stone recpie still gives sand and its on all 3 tables. by removeing the sand and such fromt the specific ones it allows u to control  stone ammounts easier. for example u can have both the hand machine and electirc side by side. the hand machine ccan be making the spcific ttypeps u use in your base and the electric can be turning the types u dont use into sand and such. makes it easy to manage.

cause sand, stone blocks,wood and meat are the most common colony killers of wealth.

**Pull request closed without merging**
