### PR TITLE
Replace Better Pawn Control v1.4 + fix Russian

### PR DESCRIPTION
**Pull request by mmavka**

### CODE REVIEW

**Comment by TheLoneTec** [comment]
so, this was kinda just leftover, im not sure this should actually be kept in, no one needed it and its really hard to make compatibility for

**Comment by mmavka** [comment]
I offered. Tested. It seems to work.

**Comment by TheLoneTec** [comment]
sure if it works, dont see why not to have it as an optional mod. QoL mods that effect the main UI can have issues with other mods, so its up to the player to sort them. Thanks for the update and translation though. :)

**Comment by mmavka** [comment]
nothing to thank

**Comment by mmavka** [comment]
You can not include it by default. And leave it to the user's choice.

**Pull request merged**
