### PR TITLE
Mining helmet cost and stat rework

### PR DESCRIPTION
**Pull request by pacas**
Also removed pointless buffs unrelated to mining

### CODE REVIEW

**Comment by pacas** [comment]
I don't know, I think with that logic you could add huge bonuses to any helmets, because it gives a sense of "militant over civilian"

**Comment by ProTriforcer** [comment]
Actually, i can see the mining helmet giving a suppressability bonus. It is known that PPE makes people complacent

**Review by AndreiAvinov — APPROVED** [review]
Less stats = easier "readability". No need to have a mash of +1% -1% stats

**Comment by TheLoneTec** [comment]
ok the reduced supressability is actually a good idea

**Pull request merged**
