### PR TITLE
disable manhunter ducks and guinea pigs

### PR DESCRIPTION
**Pull request by Voker57**

### CODE REVIEW

**Comment by ArpoMo6** [comment]
This changes could break first royalty quest Intro_Wimp (because a noble person is always pursued by small animals).

**Comment by Voker57** [comment]
> This changes could break first royalty quest Intro_Wimp (because a noble person is always pursued by small animals).

Hmm. Could you point out where small animal restriction is set in Royalty files?

**Comment by ArpoMo6** [comment]
> > This changes could break first royalty quest Intro_Wimp (because a noble person is always pursued by small animals).
> 
> Hmm. Could you point out where small animal restriction is set in Royalty files?

RimWorld\Data\Royalty\Defs\QuestScriptDefs\Intro in Script_Intro_Wimp.xml

**Comment by Voker57** [comment]
I don't see animal type restriction there, only QuestNode_ManhunterPack with one animal. It being non-small is fine by me.

**Comment by ArpoMo6** [comment]
> I don't see animal type restriction there, only QuestNode_ManhunterPack with one animal. It being non-small is fine by me.

there is Tynan commit:
image

**Comment by Voker57** [comment]
IC, thanks. What would happen if no animals could be allocated for these points?

I don't see marking animals as manhunter-enabled for this single quest as a good idea. Patch that increases points to a wolf-tier animal could be done. Perhaps someone with better knowledge can think of another solution.

**Comment by skyarkhangel** [comment]
Будем увеличивать минимальное значение для квеста?

**Comment by Voker57** [comment]
Если эксперты подскажут нужное значения, я не понимаю сколько тут надо на волка средней руки.

**Comment by ArpoMo6** [comment]
кстати, а чем не угодили мелкие зверушки в качестве агрессивных?

**Comment by Voker57** [comment]
100 мэнхантящих уток в качестве позднего рейда это как-то не очень

**Comment by ArpoMo6** [comment]
Не стоит недооценивать уток.
А так, можно поставить где-то 400-500 поинтов - в эту область попадает где-то 50-60% всех зверей ХСК (без всяких киринов, бехиров и прочего).

**Pull request closed without merging**
