### PR TITLE
CompFireOverlay Fix

### PR DESCRIPTION
**Pull request by TheLoneTec**
to hopefully stop the disappearing fire

### CODE REVIEW

**Comment by zakhad** [comment]
Shouldn't this be in the development branch rather than master?

**Comment by sidfu** [comment]
its  afix for the  fire dissapearing  that is needed in 1.3 also

**Comment by TheLoneTec** [comment]
Yeah this has been needed for a while. It was so minor thought I'd do it for 1.3 as well

**Comment by TheLoneTec** [comment]
Ill switch it to the development branch.

**Pull request closed without merging**
