### PR TITLE
Remove tincture, antibiotics, medical drinks 

### LINKED ISSUE #1933: Impossible to save antibiotics from cats
Cats try to consume antibiotics as food and get overdoses. If the tile with antibiotics and the tiles next to it are not included in their allowed zone, they will leave the zone and consume the antibiotics regardless. It's impossible to lock doors against tame animals.

Having both antibiotics and cats on the same base is unusable: cats need a pawn feeding them while overdosed, meanwhile they're quickly wasting precious antibiotics.

### PR DESCRIPTION
**Pull request by Voker57**
because they are  fakemeals and will never work properly.

Fixes #1933

### CODE REVIEW

**Comment by ArpoMo6** [comment]
I think it's not very good idea just removing some def-files. Some of them will used in new AI system (if I remember right of course)

**Comment by zakhad** [comment]
Use the pawns rules mod to make animals not consume anything you don't want them to consume, you only have to set it up once and you import the settings for each new game.

**Comment by Voker57** [comment]
> Use the pawns rules mod to make animals not consume anything you don't want them to consume, you only have to set it up once and you import the settings for each new game.

Numerous kludges to "fix" this somewhat but there is no reason for this to exist in the first place. Meals should not have such effects, otherwise it is going to be endless battle to support and fix new problems.

**Comment by sidfu** [comment]
they are not meals. they are medincie. if your anmals eat them then setup zones so they cant reach them. if your pawns eat them you  failed to setup your food menu setup. both take less than 30 sec to setup. and those meds are needed or your pawns die of disease if you dont have a good bed made out of a good leather.

**Comment by Voker57** [comment]
I don't exactly remember if I needed to remove the rest, but medical drink is a MealBeverage, which is most definitely a meal. That's, I assume, what leads to cats consuming them. They don't eat Luciferum for instance. Perhaps it could be properly implemented as a drug.

30 seconds is not enough to install a mod no idea from where and fiddle with its settings, then find out you did it wrong and cats still consume meals. It needs to be fixed the proper way.

**Comment by sidfu** [comment]
setting up a zone for animals is base game system
setting up a meal setup is also base game system.

they eat them cause they have a food value not cause they are a mealbeverage.
if i remember right the reson they have a meal setting is cause in older versions of the game to give a item thru a operation it needed to have a food value.

but that's beside the point your reasons for wanting to remove them isnt good. your reason to remove them feels like t since "i dont want to make a zone for my animals it should be removed...."

**Comment by Voker57** [comment]
> setting up a zone for animals is base game system
> setting up a meal setup is also base game system.
> 
> they eat them cause they have a food value not cause they are a mealbeverage.
> if i remember right the reson they have a meal setting is cause in older versions of the game to give a item thru a operation it needed to have a food value.
> 
> but that's beside the point your reasons for wanting to remove them isnt good. your reason to remove them feels like t since "i dont want to make a zone for my animals it should be removed...."

Setting up a zone or meal system should not be required for basic stuff. It's like colonists start eating their own limbs because they have a food value unless you download mod "Disable Limb Eating" and configure it. If HS ships some other way of not having animals overdose on antibiotics for no reason at all, good. Otherwise, it is misconfigured and I'm suggesting a non-perfect way to solve it. Feel free to make a better PR.

**Comment by zakhad** [comment]
The antibiotic from disease overhaul Tritoxylon/Fluoroquinolone has the proper method for how antibiotics should be implemented into the pack. It just needs someone to copy the code out of it or adapt the changes from it to seperate how we've done medical tinctures/antibiotics, since animals won't decide to eat it and it boosts immunity gain, but until someone does that don't delete the current method of boosting immunity gain as there is no alternative currently.

**Pull request closed without merging**
