### PR TITLE
Add royalty tags to new floors and beds

### PR DESCRIPTION
**Pull request by Voker57**

### CODE REVIEW

**Comment by ArpoMo6** [comment]
Some floors already have a patch "Fine floor" (RimWorld\Mods\Core_SK\Royalty\Patches\ThingDefs_Buildings in PatchesFineFloors.xml).
These edits may cause this tag to be duplicated.

**Comment by Voker57** [comment]
I think I already removed solid gold floor because of that double tags thing, others do not intersect. But thanks for the patch location.

**Comment by ArpoMo6** [comment]
All royalties patch should be in Royalty folder or have Find mod Royalty.

This patch will try to work without Royalty and will cause red errors:
image

**Comment by Voker57** [comment]
Added FindMod for Royalty.

**Pull request merged**
