### PR TITLE
Remove unnecessary "Beauty: n" or "Fertility: n%".

### PR DESCRIPTION
**Pull request by gezinfly**
As you can see in the screenshot below: 
图片
As the "Beauty: n" or "Fertility: n%" have been displayed by Moreinfobox.dll in coreSK, these components in descriptions are unnecessary and even some of them outdated.

In this pull request, I tried to remove them, including those in Defs and Languages. I hope there is nothing left...

### CODE REVIEW

**Comment by ArpoMo6** [comment]
Hello! Thanks for you great contribution, but can you please fix this. Missed one "<" after changing in Korean localization:

image

It may even cause the game to crash on startup.

**Comment by gezinfly** [comment]
I am so sorry. 
Thank you very much!
I'm shouldn't forgot to give it a f**king test! I will never do that again.
I'm try to update my local game now. Wait for me...

**Comment by gezinfly** [comment]
**I can't download**

**Comment by gezinfly** [comment]
Though I still can NOT download zip because of some network problem, I reviewed the files and didn't find more issues.

**Pull request merged**
