### PR TITLE
Idle from/to full power consumption on electric things.

### PR DESCRIPTION
**Pull request by olizit**
Add <tickerType>Normal</tickerType> tag on every things which require
power.
see issue: Work stations drawing full power when idle #100

### CODE REVIEW

**Comment by jnkyacc** [comment]
Any performance impact(late game)?

**Comment by olizit** [comment]
I don't test with many building site which require power but I will test.

**Comment by olizit** [comment]
I don't sure to understand well your post.
Actually before my PR for example ComponentAssemblyBench works as expected. 
On idle production site draw =basePowerConsumption * idlePowerFactor. If pawn works production site draw full power (=basePowerConsumption).
My PR extand this behaviour to all electric production site.
Flick on/off seems to work well.

**Comment by olizit** [comment]
> Any performance impact(late game)?
I test with 20 production site. They turn to idle state one by one within few seconds.

**Pull request merged**
