### PR TITLE
Add Recipe - make Artificial Bones(4x)

### PR DESCRIPTION
**Pull request by Watcher011**
Added recipe for mass production of artificial bones (4 pieces)

### CODE REVIEW

**Comment by Watcher011** [comment]
needs improvement

**Comment by ProTriforcer** [comment]
It sure does. You could have converted it to draft instead of closing though.

**Comment by Watcher011** [comment]
I'm just starting to learn the features of working with Github and I'm afraid of doing something wrong

**Comment by Watcher011** [comment]
-

**Pull request closed without merging**
