### PR TITLE
huge texture compression (-150mb, 100% quality, so everything must be ok)

### PR DESCRIPTION
**Pull request by GuardianDll**
Массивное сжатие текстур (-150мб при 100% качестве, так что никакой разницы в качестве не будет)

### CODE REVIEW

**Comment by zakhad** [comment]
While the file size might be smaller won't loading times be longer?

**Comment by ArpoMo6** [comment]
@zakhad I've played with all HSK texture compressed ~3-4 month. Loading time is same.

**Comment by GuardianDll** [comment]
ok, looks like everything is okay

**Comment by GuardianDll** [comment]
Stupid fucking soursetree

**Pull request closed without merging**
