### PR TITLE
Food Preservation

### PR DESCRIPTION
**Pull request by AndreiAvinov**
Ok, problem: food preservation is kinda useless, coldstone is too good and extremely effective alternative to freezers.
Solution: 
- Changed early game preservation, meat jerkies and dried fruits no longer give debuff to mood
- Changed meat jerkies to be produced from usual and not salted meat
- Change numbers on drying racks, now production effficiency is about 90% (you get about 0.9 preserved nutrition for every 1.0 of raw products) 
- Coldstone battery now cools down surrounding area to ~~0C~~ -3C (was -5C)
- Increased cooling speed of coldstone battery to compensate
- Tweaked salted meat recipe to better match new mechanic

Preserving food this way creates some additional micromanage - choosing what part of food to preserve and what part to cook right away. Drying stuff is when you don't have enough time with your cooks and you just want to save nutrition for bad days, salting meat is when your cook has enough time, another pawn has time to mine salt and you want to get more nutrition from this meat in the long run. 
Pro tip: place a campfire together with drying racks in a room - this way tempreture will almost always stay at ideal level.

---------------------

Сохранение остатков еды в хск работает несколько криво и несбалансированно, а хладокаменная батарея полностью убивает надобность в этой механике. 
Предлагаю:
- Изменить сушёное мясо и фрукты, они больше не дают штраф к настроению за поедание 
- Изменить рецепт сушёного мяса, производить его из обычного мяса, а не засоленного 
- Изменить цифры на сушилках, теперь эффективность преобразования примерно 90% (из 1.0 питательности получится примерно 0.9 долгохранящейся питательности)
- Хладокаменная батарея теперь охлаждает окружение до ~~0~~ -3 градусов (было до -5). 
- Увеличил скорость охлаждения батареей для компенсации изменений
- Немного изменить рецепт засолки мяса чтобы лучше подходило новой механике.

Такие изменения добавят новый слой контроля на раннем этапе - будет выбор между высушиванием еды для экономии времени повара, либо засолкой (мяса) для последующего использования в рецептах чтобы получить немного больше общей питательности.

### CODE REVIEW

**Comment by Zim777** [comment]
Категорически против хладобатареи в таком виде. Это единственное, что позволяет жить на племени. И до ближайшего холодильника жить придется по 5-6 лет порой. 
Даже с карманами, шлюзами, двойными стенами и тд в той же пустыне и так приходится строить их по 3-5 штук чтобы держать и хладокамень улетает вмиг.

**Comment by zakhad** [comment]
The only reason people use coldstone is because making jerky requires salted meat (Which is anathema because salting takes too long, and getting ahold of salt also takes long), simply making jerky from raw meat and you'll see a lot of people doing it. You should test to see how people react with just the raw meat into jerky, before nerfing coldstone imo and even then -5 to 0c is quite a huge change, go to like -2, then to 0 afterwards if it still doesn't have the desired result in the community.

**Comment by AndreiAvinov** [comment]
Ok, so I reversed some nurfs to Coldstome battery - it gives -3 tempreture, but at increased effectiveness. As to meat jerky - I made it so it is inefficient to dry all your meat and not cook it at all, but for any leftovers that otherwise would spoil - it is fine, I guess.

Изменил часть с хладокаменной батареей, теперь даёт -3 градуса, но с увеличенной эффективностью. С сушёным мясом всё в порядке - у сушки сравнительно низкая эффективность и готовить то что успеваешь съесть - гораздо выгоднее

**Comment by sidfu** [comment]
the reason jerky is like it is is cause if u allow it out of nothing but meat people will build 99999 drying racks and use nothing but jerky and ignore  needing any other type of food. instead of buffing jerky to be the god food again just lower the amount of salt needed for it. salt is gotten plenty but for maps with few hills/mountains.

this isnt pre 64x days where caravan means your game ctd and u spend  a hour loading. salt is set4 to be as common as copper nearly. u can easily jump on a caravan go to some temp maps and hunt while u look for salt.

here what u should do
1. increase amount u can salt at a time and lower the salt amount(drying rack is faily balanced on temps now)
2. efficiency should be no higher than .8 this represents a good balance vs not making it to hard and shows the loss u get from some going instead bad of curing/bugs getting into it.
3.for coldstone set it to just refrig stuff not freeze and it be balanced
4. to help with preservation since people dont know u dont have to butcher every animal the moment its dead u can add canning a bit sooner.

well none of this matters since most just eat raw food for a few years anyway.

**Comment by AndreiAvinov** [comment]
> and use nothing but jerky and ignore needing any other type of food

I mean I can't stop people from making their life harder
> efficiency should be no higher than .8 this represents a good balance vs not making it to hard and shows the loss u get from some going instead bad of curing/bugs getting into it.

It will just make that people will never use racks. Me included. Drying food is already quite a commitement in a sence that you can't cook dried food into anything else.
> for coldstone set it to just refrig stuff not freeze and it be balanced

People will eat me, it is to big of a change for now

**Comment by sidfu** [comment]
.8 will not mean people wont use them. people dont use them cause its not a "god food" anymore. jerky is a completed meal/snack type. it isnt meant to be used in other meals.
jerky is suppose to be a investment to make not some free easy way to get food and never need a cook.

raising the amount of salted meat u can make=fine
lowering salt/another way to get salt= fine
removing the mood debuff = fine (dont remrme4ber when we added that to it)
raising the effeincy= bad it unbalance it making it to  easy to get.
using raw meat= bad  even in real life they dont use raw meat without spices added

for cold stone its what they have to get use to. its called balance. coldstone isnt meant to freeze food its suppose to be a tool to help early game not something u use from tribal till u get into space. its something that ha a niche use and once u grow out of it u replace it same wtih the glowstone lamps.

**Comment by AndreiAvinov** [comment]
@sidfu I mean it was 300% nutrition efficiency for jerkies, now it is around 90%

**Comment by zakhad** [comment]
The current problem is that jerky doesn't get used, the investment is entirely not worth it by the overwhelming majority of players.

My main problem is that the job itself is asinine to make the actual salting of meat job; it's ungodly slow.

Any job that is slow in SK is baaaaaaaaaad like literally the WORST thing about this modpack bad if you fail to make something due to a mental break/raid your currently job might as well be for naught because it's not like the apparel/ammo/weapons where they can be resumed. And it's not even a meal. You've still got to put it on a rack afterwords and make sure it's a temperature controlled room which is quite difficult pre electricity, unless you're in an "ideal" biome. The temperature shift between day/night usually ends up binning my tribal jerky motivation, campfire you say? No it doesn't last long enough even with firewood.

We need dusty to make us some sunstones \o/ that raise temperature because.... well we already have magical stones that radiate cold :S

I would do something like 1 salt 5 meat = 5 salted meat a reasonably fast job, but on a dedicated table or spot in on itself that doesn't get effected by temperature, so you can do the job inside the meat storage fridge/freezer, so there is no going in and out and leaking temperature that's also a consideration of why I don't do the job.

My gut feeling about this is that there is a lot of controversy / different opinions on jerky making an overhauling jerky - it can be done in another commit but honestly I don't have a problem, I'm always up for changing the status quo - it can be fixed in another commit if it gets abused.

I would suggest making a new recipe where we "Smoke" or "Dry" the meat and it lasts like 15 days, but doesn't require salt and can be shoved on the rack directly or be done at the oven (I really dislike how it's only used for bread mostly it needs more love) as a mediocre method of preserving meat not long term but short term, that on top of a fridge like cold stone environment would give like 60 days or so of meat so that works or something along them lines.

**Pull request merged**
