### PR TITLE
Updated Weapon_Melee.xml

### PR DESCRIPTION
**Pull request by PoppyLoveU**
Added recipeMaker for MeleeWeaponUltratech ，Enhance market value

### CODE REVIEW

**Comment by TheLoneTec** [comment]
So, from what i rememeber, these were supposed to be non-craftable items. The only reason a stuffCategory was added, was because they were smeltable.

**Comment by pacas** [comment]
These weapons 100% supposed to be non-craftable, to keep them sort of like quest / Empire exclusive. For the manual crafting there is a wraith blade. IF you want them to be craftable, you can push this as an addon.

**Comment by zakhad** [comment]
Better off as a mod in the discord.

**Comment by masakitenchi** [comment]
It's made to compensate how vanilla calculate an item's market value (See `StatWorker_MarketValue.GetValueUnfinalized` and `StatWorker_MarketValue.CalculatedBaseMarketValue`).

# Explanation
For any item that doesn't have a recipe, it uses the pre-defined market value. I don't remember how vanilla does, but since there aren't a stuff option in vanilla, it's fine for them to have a pre-defined market value. 
No matter if HSK made then stuffable or not, the uniformed market value made its market value sometimes ridiculous ($1000 for both plasteel and alpha poly monosword iirc, not accounting for diffuculty adjustment and anything that postfixes its market value)

So we had a discussion about how to refine the economy system, this is the first (I guess) answer. The RecipeDefs aren't supposed to link to any workbench, so it still cannot be crafted, but removing the pre-defined market value and adding RecipeDef that produces it make sure the game now will calculate its market value using given ingredient list and the work amount needed to produce it

Haven't tested on my side though, so the value could be tweaked later

**Comment by TheLoneTec** [comment]
if thats the case then the recipeUsers need removing

		<recipeUsers>
			<li>MechWeaponCraftingWorkTable</li>
		</recipeUsers>

**Comment by masakitenchi** [comment]
As I've said a while back, changing the price would result in empire faction pawnkinds missing melee weapons. Patch their weapon money and we can move to the next stage.

**Comment by TheLoneTec** [comment]
The best way to test this is to run the game with these changes, put the weaponMoney back to how it was and the game will complain in the log if the weaponMoney values are too low. It will gibe you the minimum, you can then adjust the range to meet the minimum, with the same range just moved up slightly. If that makes sense.

**Comment by PoppyLoveU** [comment]
The minimum value displayed in the game is 10180 so I raised it to 11000.Now game log no complain.

**Comment by TheLoneTec** [comment]
The best way to test this is to run the game with these changes, put the weaponMoney back to how it was and the game will complain in the log if the weaponMoney values are too low. It will gibe you the minimum, you can then adjust the range to meet the minimum, with the same range just moved up slightly. If that makes sense.wow, that is expensive, have you tried spawning those pawnkinds to see if their Weapons remain the same?

**Comment by TheLoneTec** [comment]
Sorry, for some reason, the mobile app saves your previous comments you wrote for some stupid reason. But yeah. I would try spawning these pawnkinds, making sure  they don't get anything crazy

**Comment by PoppyLoveU** [comment]
I tested and found that there is no difference from before. They still only carry melee weapons, such as Monoword

**Comment by TheLoneTec** [comment]
ok, looks good

**Pull request merged**
