### PR TITLE
Fix Timbershroom and Bonsai tree not sowable.

### PR DESCRIPTION
**Pull request by TheLonerD**
Allow `Plant_Timbershroom` and `Plant_TreeBonsai` to sow in any biome with seeds.

### CODE REVIEW

**Comment by TheLoneTec** [comment]
im 99% certain this is intentional

**Comment by TheLoneTec** [comment]
Timershroom isnt supposed to be plantable (if you want that, there are mods for it). And the bonsai is a decorative plant like flowers.

**Comment by TheLonerD** [comment]
And you can't plant bonsai tree with seeds mod enabled.

**Comment by zakhad** [comment]
I'm not merging this and rejecting it because Master and development are for 1.3 and have otherwise stopped actively being developed, baring critical bug fixes. any new coding goes into the 1.4 alpha branch it otherwise becomes a nightmare to merge conflicting branches between two versions when they're both being developed.

**Pull request closed without merging**
