### PR TITLE
Remove extra small and stupid animals

### LINKED ISSUE #1929: Flies and mosquitoes quickly consume all the starting survival food
As seen when starting in jungles. This doesn't seem plausible since the insects are tiny, and there aren't that many of them.

### PR DESCRIPTION
**Pull request by Voker57**
Engine is not suitable for such small entities, making them behave in unrealistic and annoying ways.

Fixes #1929

### CODE REVIEW

**Comment by skyarkhangel** [comment]
i suggest to make a separate mod with removal patch.

**Comment by Voker57** [comment]
Sorry, too much effort for me and I think these should be obliterated from the modpack and Core_SK.dll (how about the source code btw?) completely.

**Comment by ArpoMo6** [comment]
Simply removing mosquitoes and flies from biomes can break epidemic events.
If you really dislikes this animals, you can use this patch from discord #patches-1-2 channel
https://discord.com/channels/272340793174392832/745746107329413121/790579521820426281

**Comment by Voker57** [comment]
Plague works fine without insects, I assume malaria does as well. I'd be happy to remove/fix the events too, but again no source code ;-)

**Pull request closed without merging**
