### PR TITLE
Added The enemy of my enemy is my friend mod

### PR DESCRIPTION
**Pull request by ArpoMo6**
This modification unites all factions hostile by default with each other, making them allies or neutrals in relation to each other. If hostile raids from different factions happen at the same time, they will jointly attack the player.

Модификация объединяет все враждебные по умолчанию фракции между собой, делая их союзниками или нейтралами по отношению друг к другу. Если враждебные рейды разных фракций окажутся в одно время на вашей карте, они будут совместно нападать на вас.

### CODE REVIEW

**Comment by Zim777** [comment]
А между собой у них будут портится отношения, если они будут попадать друг в друга? или они перманентно между собой союзники?

**Comment by zakhad** [comment]
I'm of the opinion that this should not be included in the modpack even if it is optional, it should be a patched mod in the discord channel, as it drastically changes the balance of the game, raids are hard enough as it is, if they all band together that's going throw the balance. We another such mod DarkestNightSK, where it radically arguably makes the game far more tedcious than it needs to be (Some people enjoy this it's fine, not a complaint per se) but the overwhelming majoirty of people do not like this mod and i feel like adding another such mod will start to skew how the modpack is viewed, it is called hardcore but that has thrown people off trying this modpack i believe adding more of these types of mods that radically change the difficulty will hurt the modpack by being included.

As the average user googles rimworld modpack might find a steam collection, then they start suddenly  hearing whispers about this about the Russian dark alley cult modpack called HSK (we have a very dubious reputation in the official discord) and i would like to change that by being more inviting and not have so many mods included that can really throw the balance. Most people don't know what these mods do and won't even look at the description, and simply enable them all, and they're going to have a negative experience because they're just looking for more "content" not necessarily difficulty, and more mods = more content they don't read between the lines, and i believe it is our job to cater to a good overall user experience, and i'm of the opinion that adding this mod to the modpack will add more negative than positive energy to the users/community, which is why i believe it should be a seperate mod in the patches channel in discord.

But

If other developers disagree and think it should be then they can merge it in, but I would ask/request that there is a majority consensus and not a single opinion of a collaborator who merges this in i,e @Glucocorticoid or @sidfu

**Comment by Spaniard829** [comment]
> it drastically changes the balance of the game

In my experience, even on maximum difficulty, the situation when there are raids from different factions on the map at the same time does not occur very often, and perhaps this PR will not change anything at all. Although, if you have other information, please write in what conditions this happens.


> overwhelming majoirty of people do not like this mod

Totally disagree. I'm sure a lot of people use the mod and don't talk about it. The use of the words "overwhelming majoirty" can be misleading to other people. It's complicated, but we should try to be as objective as possible when talking about changes to this repository. I think this is the right thing to do if we want HSK to be of interest to more people.


> Most people don't know what these mods do and won't even look at the description, and simply enable them all

This is their responsibility.
Perhaps we should add more detailed descriptions to the modifications, perhaps separate guides where the impact of the modification on the difficulty level will be analyzed. But not adding a modification for this reason is not very smart. _As enabling modifications without reading the descriptions and not knowing what they change, and then get upset about the result._


> If other developers disagree and think it should be

I think maybe these changes should go into Core_SK. This is the idea of ​​alliances. The extent of the impact is not yet clear. Tests will help.


I think Sky decides what the project should look like. Because balance is subjective.
In my opinion, at the moment, even without additional mods, the balance needs serious improvements.

**Comment by TheLoneTec** [comment]
it depends how its done. personally i think it should be seperate to Core_SK, as there are some mods that already add this functionality. So for the sake of preference and compatibility, i feel it would be best having it optional, dont mind it being included though. Just my take.

**Comment by zakhad** [comment]
> > it drastically changes the balance of the game
> 
> In my experience, even on maximum difficulty, the situation when there are raids from different factions on the map at the same time does not occur very often, and perhaps this PR will not change anything at all. Although, if you have other information, please write in what conditions this happens.
> 

The raid assist doesn't always trigger the same faction as a reinforcement raid, (Perhaps a bug?) sometimes it's my own saving grace is that they end up fighting each other, I'd imagine that if you're in a middle of a quest (raid based) and a raid happens, and then a reinforcement raid happens (to both the quest raid, and the regular raid) and they happen to be allies now because of this mod (Which depends on factions it's not always going to be the case) your going to get  overwhelmed pretty quickly because you're now dealing with 4 raids that are all friendly to each other, or potentially have the potential to be friendly if it lines up as such. 

> > overwhelming majority of people do not like this mod
> 
> Totally disagree. I'm sure a lot of people use the mod and don't talk about it. The use of the words "overwhelming majoirty" can be misleading to other people. It's complicated, but we should try to be as objective as possible when talking about changes to this repository. I think this is the right thing to do if we want HSK to be of interest to more people.
> 

Yes it was misleading i take that back sorry, but i do feel like and have seen "a lot" (English channels) of people do dislike the darknessSK mostly because they don't know how to deal with it, once they know how it works, they're generally okay with it, and it's down to whether or not they want to add more checks and balances to the game i,e having light sources up and ready. 

Personally i often get caught out with pawns out in the field and it's basically almost instant death for them as they won't be able to get back to base in time it's not like i'm not going to give each pawn a torch on their loadout (Tbh i've never tried i assume they'd weight a lot?) and even then unless you have several in multiple directions depending on the gamespeed they can just ignore the light and still hit the pawn going through like 5-10 tiles of light, sure there is a expected cut off point but when your out in the "sticks" (outside the base out in the wilderness, if that doesn't translate) that's not really a viable option. 

> > Most people don't know what these mods do and won't even look at the description, and simply enable them all
> 
> This is their responsibility. Perhaps we should add more detailed descriptions to the modifications, perhaps separate guides where the impact of the modification on the difficulty level will be analyzed. But not adding a modification for this reason is not very smart. _As enabling modifications without reading the descriptions and not knowing what they change, and then get upset about the result._
>

Sure if the description is much more clear that it's a "difficulty challenge mod" or something that makes it painfully obvious that it might cause them to read the description.  I don't see people giving the modpack a second chance as it were if they have a bad experience because, yeah it was their fault for not reading what the individual mods do, but to lose that investment/immersion by disabling to removing the mod in order to start over or reload, people give up at that point especially when your new, first impressions are so important. HSK takes a lot of investment and or time to progress when your mid game you suddenly get overwhelmed because of said mod that wasn't obvious then they just end up throwing hate and or disdain, they're not going to blame themselves because who blames themselves, people don't take credit for their own mistakes. If the mod is made very apparent of what it does then there is no problem, and there is only so much we can do to mitigate user error.

> 
> > If other developers disagree and think it should be
> 
> I think maybe these changes should go into Core_SK. This is the idea of ​​alliances. The extent of the impact is not yet clear. Tests will help.
> 
> I think Sky decides what the project should look like. Because balance is subjective. In my opinion, at the moment, even without additional mods, the balance needs serious improvements.
>

Ultimately it is up to Sky, i wasn't trying to come across like i dictate what does or doesn't go in the modpack. I was starting problems i see with it and my hesitation for it, and perhaps it would be better as a outside mod at first, then added into the pack rather than just adding it straight in, because of a potential forecast of how users might react to it.

**Comment by Spaniard829** [comment]
> The raid assist doesn't always trigger the same faction as a reinforcement raid, (Perhaps a bug?) 

I'm sure it's a bug.

I propose to add the first line to the mod description: "Experimental, can greatly increase the difficulty of the game". In red.
If that's not enough, I suggest leaving the decision to Sky.
__
@Zim777, надо тестировать, пока не ясно. В идеале должны оставаться союзниками.

**Comment by zakhad** [comment]
If Sky doesn't come around idk in say in a few days under the assumption he's still away busy with real life, to chime in his thoughts, and or be the arbiter then i will merge it, if no one else has. It is optional after all. You made me more receptive towards including it @Spaniard829 and hopefully the description modification/warning is enough. 

More people chiming in on what they think of this would be appreciated.

**Pull request merged**
