### PR TITLE
updated minerals to v0.4.2

### PR DESCRIPTION
**Pull request by zachary-foster**
## v0.4.2 

**compatible with existing saves**

### Aditions:

* 7 new static minerals: Tourmaline group
* 2 new minerals: growning sulfur and larger static sulfur
* 4 new static minerals: Corundum group
* 6 new static minerals: Beryl group
* 2 new static minerals: Magnetite and lodestone
* 1 new static minerals: Diamonds
* 2 new static minerals: Malachite and Azurite
* 1 new static minerals: Uraninite
* 1 new static minerals: Cassiterite

### Improvements:

* New print method now uses normal distributions, so clusters look more natural
* "neededNearbyTerrains" now can be used with "things" like buildingd and steam geysers.
* Minerals can now stack on eachother

### Changes

* Increased gem drop rate a bit
* increased rough gem and gem value 
* Made flint less pretty
* Increased sharp stone stack count to 150
* Quartz is now outside of caves as well
* increased yield of flint nodules and obsidian
* Lots of other small adjustments 

### Bug fixes:

* Ice stalagmites dont drop sand anymore

### CODE REVIEW

**Comment by zachary-foster** [comment]
Found a bug. Minerals go to 100% size after save/load. I will resubmit when fixed.

**Comment by skyarkhangel** [comment]
Ok. Check vars and add needed to exposed data for saving.
Also, need to think.. Need we a lot of types of minerals?

**Comment by zakhad** [comment]
The spawn rate needs be down to like 25% of what it is because there are minerals all over the map

**Comment by zachary-foster** [comment]
> Ok. Check vars and add needed to exposed data for saving.

I fixed it I think, but I want to test more. 

> Also, need to think.. Need we a lot of types of minerals?

Probably not as many as I added. I can remove some of the more redundant ones if you like. I just like the diversity, but if it will slow things, I don't mind removing some. 

I would like to keep the ore-producing ones:

* Malachite = copper ore
* Uraninite = uranium ore
* Cassiterite = tin ore
* Magnetite = iron ore
* Lodestone = magnetic material

I dont mind removing these:

* larger static sulfur
* Prasiolite
* Azurite
* Beryl or Corundum group, since they are pretty similar. I would like to keep some though, because they have the well-known gemstones ruby, sapphire, and emerald

> The spawn rate needs be down to like 25% of what it is because there are minerals all over the map

Yea, I agree, I will lower it.
It was ok before I added all those, but its a bit much now. 


What causes more lag or other problems: more image types or more defs? Many minerals share the same image with different colors

**Comment by zachary-foster** [comment]
You can look hear for images and descriptions of each: 

https://github.com/zachary-foster/Minerals

**Comment by zachary-foster** [comment]
How about an additional "Extra Minerals" mod that is disabled by default?

**Comment by zakhad** [comment]
Yeah that sounds better with the extra minerals being a separate companion mod

**Comment by zachary-foster** [comment]
Nice, I think I will do that before another PR. That way I can add whatever I want and the main mod can just include minerals with unique uses/appearance

**Pull request closed without merging**
