### PR TITLE
Russian fix (Android)

### PR DESCRIPTION
**Pull request by mmavka**
Russian fix (Android, AnimalsAreFun, DismissTrader)
Fix Double Defs Bsalt
Fix ModsConfig

### CODE REVIEW

**Comment by mmavka** [comment]
Don't marge... i have crash game....

**Comment by mmavka** [comment]
I'll watch it later

**Comment by zakhad** [comment]
Why are you deleting korean and spanish translations?

**Comment by mmavka** [comment]
rename folder.... hmmm...

**Comment by mmavka** [comment]
strange. files are in Unversioned

**Comment by mmavka** [comment]
русский?

**Comment by zakhad** [comment]
Нет, но при необходимости пропускаю все через переводчика, что иногда вызывает некоторые сомнения, но это понятно. Какого рода сбои вы получали с языковыми файлами? Вы уверены, что это было связано с языковыми файлами, что кажется странным.

**Comment by mmavka** [comment]
Yes, it seems strange to me too. I try spawn AsariColonist and everything is fine. If I try spawn AsariCommando or any other Asari. The game freezes and crashes. The logs don't say anything.

**Comment by zakhad** [comment]
Any errors on startup related to them? Tried disabling Asari mod etc, basically i'm uncertain whether or not to merge this in, it seems unrelated and coincidental that a translation file could be the cause, have you tried doing the same but in english? to verify that it is when you turn to русский that it causes it?

**Comment by TheLoneTec** [comment]
i just tried spawning an Asari Commando and it crashed, no error. Im using english obviously, so its not the translation files

**Comment by mmavka** [comment]
english crash too.

**Comment by zakhad** [comment]
Okay it's unrelated i will merge, which i thought was the cause.

**Comment by TheLoneTec** [comment]
means something is wrong with the asari though :(

**Pull request merged**
