### PR TITLE
New sword fern textures

### PR DESCRIPTION
**Pull request by zachary-foster**
Removed shadow and debris from old textures. Added two new textures. Increased range of redwood sizes, since small redwoods were much bigger than pines. 

I made snowy textures for the ferns, but I could not figure out how to make them work right. If I make them "leafless" they show when it is cold, rather than if it is snowing. I will attach them here in case anyone known how to make it work right. I will try to get them to work later. 

This will require a change to the "NPS_SK" mod since I renamed "SwordFern" to "PlantSwordFern".

swordfernd_snowy
swordfernc_snowy
swordfernb_snowy
swordferna_snowy
plantswordferne_snowy

### CODE REVIEW

**Comment by skyarkhangel** [comment]
i suggest to remove doubled.. and set for this plant: <maxMeshCount>4</maxMeshCount>

**Comment by zachary-foster** [comment]
Thanks for the advice! I will try that

**Comment by skyarkhangel** [comment]
i'll added it withsome changes.

**Comment by zachary-foster** [comment]
Thanks! You're welcome to use them however you find useful. I added the double textures to break up the grid pattern when there is 1 max mesh, but that might not be an issue with max mesh of 4. Let me know if you want the source .xcf files made in gimp with the layers.

**Comment by zachary-foster** [comment]
By the way, I am super happy with the Redwoods biome in NPS and the swordfern texture being used there!

**Pull request closed without merging**
