### PR TITLE
Fixed typo in xml and dll

### PR DESCRIPTION
**Pull request by AndreiAvinov**

### CODE REVIEW

**Comment by AndreiAvinov** [comment]
Also added ru translation mods to load order. No more black screens on load.

**Comment by TheLoneTec** [comment]
i swear these xml changes have been done like 3 times now..

**Comment by TheLoneTec** [comment]
wait, why did you revert the correction?

**Comment by AndreiAvinov** [comment]
@TheLoneTec Yeah, I saw Masaki's changes, but they were still wrong and dll had wrong spelling too

**Comment by TheLoneTec** [comment]
yeah i dont know how this happened, i for sure thought i saw him correct the spelling

**Pull request closed without merging**
