### PR TITLE
Changed drop from Crushed Shuttle from matte to steel

### PR DESCRIPTION
**Pull request by MrProvokator**

### CODE REVIEW

**Comment by masakitenchi** [comment]
Any reason why? I personally don't think shuttle uses stronger materials is a bad idea

**Comment by sidfu** [comment]
its probably cause of the issue where you can get the shuttle and they get attacked by tribals....
the quest highly suffers from the base game issue of it loves to send tribals for everything

**Comment by TheLoneTec** [comment]
what is this "matte"?

**Comment by TheLoneTec** [comment]
guessing you mean "stein alloy"?

**Comment by MrProvokator** [comment]
@TheLoneTec Yes, stein, wasn't sure what it was called in the English version :)

**Pull request merged**
