### PR TITLE
Integrate Deep Storage support into Bill config UI

### PR DESCRIPTION
**Pull request by ZB333ZB**
feat: Enhanced bill config with Deep Storage integration

Key changes:
- Replaced vanilla "Take from"/"Bring to" buttons with custom storage selector
- Added dedicated storage selection frame in the central column
- Implemented popup dialog for storage/stockpile selection with search
- Added detailed tooltips showing stack/cell info and inventory

Technical details:
- Complete UX/UI overhaul of bill config dialog
- Retained core vanilla components while rebuilding interface
- Added fallback behavior for incompatible storage filters
- Implemented warning messages for failed storage attempts

Storage selector features:
- Dynamic list of available storages/stockpiles
- Real-time search functionality
- Hover tooltips with capacity metrics
- Current inventory display
- Visual feedback on selection

Note: Storage/stockpile filtering by allowed items pending implementation if needed.

Known behaviors:
- Shows all storage options regardless of filter compatibility
- Items drop to ground if target storage filter incompatible
- Warning messages notify player of storage mismatches

Feedback welcome on UX improvements and additional features.

---
1a
1b
1c
1d
1e

### CODE REVIEW

**Comment by ProTriforcer** [comment]
Does it support storage groups (the "link settings" button)? It probably should

**Comment by ZB333ZB** [comment]
Yes, I've just tested it. I don't see any issues with linked storages

**Comment by ProTriforcer** [comment]
I mean, can you select a whole storage group instead of just one pallet?

**Comment by ZB333ZB** [comment]
No, currently in the popup window you can only select individual storage units. I didn't initially plan for this feature. Again, there's quite a wide range of potential improvements that could be implemented in the future

**Comment by ZB333ZB** [comment]
The tricky part with linked storage groups is that they lack labels unlike regular storages, so StorageSelector can't search them properly. Need to implement a labeling gizmo for these groups to make them discoverable in the selector UI

**Pull request merged**
